[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_timekeeping"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
ESP_IDF_GLOB_PARTITION_TABLE_BASE = { value = "", relative = true }
ESP_IDF_GLOB_PARTITION_TABLE_CSV = "partitions.csv"
